version: '3.8'

# networks:
#   app-tier:
#     driver: bridge

services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_DATABASE=proto_parser_db
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=password123

  gcs-mock:
    image: fsouza/fake-gcs-server
    ports:
      - 4443:4443
    volumes:
      - ${PWD}/data:/data
    entrypoint: ["/bin/fake-gcs-server", "-data", "/data", "-scheme", "http", "-public-host", "localhost:4443"]
